---
name: Merge

on:
  push:
    branches:
      - main

jobs:
  gettext:
    name: Gettext
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:8.2
      options: --privileged

    steps:
    - name: Install git, python3-git and jq
      run: |
        apt-get update
        apt-get install git jq python3-git -y

    - name: Clone repository
      uses: actions/checkout@v6
      with:
        token: ${{ secrets.GIT_USER_TOKEN }}

    - name: Configure Git
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Update Translation Files
      uses: elementary/actions/gettext-flatpak@main
      with:
        manifest-path: io.github.ellie_commons.sequeler.json
      env:
        GIT_USER_NAME: "github-actions[bot]"
        GIT_USER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
